// Generated by CoffeeScript 1.6.2
(function() {
  var ExportSettings;

  ko.components.register('exportSettings', {
    viewModel: ExportSettings = (function() {
      function ExportSettings() {}

      return ExportSettings;

    })(),
    template: {
      require: "/static/requirejs/text.js!views?template=settings/exportsettings/exportsettings"
    }
  });

}).call(this);

/*
//@ sourceMappingURL=exportsettings.map
*/
