// Generated by CoffeeScript 1.6.2
(function() {
  window.testSuite = [
    {
      call: "listInstances",
      params: ""
    }
  ];

}).call(this);

/*
//@ sourceMappingURL=performancetasks.map
*/
