window.testSuite =
  [
    {call:"generateSSLCSR",params:null},
#    {call:"getSysLogServerInfo",params:null},
    {call:"getKeySecureProperties",params:null},
#    {call:"disableNTP",params:null},
    {call:"getVersion",params:null},
#    {call:"enableSyslogForwarding",params:null},
    {call:"getStatusOverview",params:null},
    {call:"unregisterAllPeers",params:null},
#    {call:"disableSyslogForwarding",params:null},
#    {call:"deleteProxyConfig",params:null},
    {call:"listProtectedInstances",params:null},
    {call:"getAggregateRefreshRate",params:null},
    {call:"getMaxOfflinePeriod",params:null},
    {call:"eulaText",params:null},
    {call:"listCloudCredentials",params:null},
    {call:"listDNS",params:null},
    {call:"enablePhysicalServerSupport",params:null},
    {call:"getSNMPTrapConfig",params:null},
#    {call:"applyNetworkChanges",params:null},
    {call:"listSupportedClouds",params:null},
    {call:"getAutoUpdateIpFlag",params:null},
    {call:"getNTPState",params:null},
    {call:"eulaAccept",params:null},
#    {call:"disableUnattendedRebootAll",params:null},
    {call:"listNetworkInterfaces",params:null},
    {call:"getHaHeartBeatConfig",params:null},
    {call:"getKeySecureCredentials",params:null},
    {call:"getPhysicalServerStatus",params:null},
    {call:"getSystemStatusOverview",params:null},
    {call:"enableSNMPTraps",params:null},
    {call:"server_restartGuiService",params:null},
    {call:"getFirstRunNextStep",params:null},
    {call:"listRoles",params:null},
#    {call:"shutdownSystem",params:null},
    {call:"getComplianceReport",params:null},
    {call:"listUsers",params:null},
    {call:"disablePhysicalServerSupport",params:null},
#    {call:"suspendUnattendedReboot",params:null},
    {call:"getInstancePollInterval",params:null},
    {call:"getCurrentPermissions",params:null},
    {call:"isEulaDone",params:null},
    {call:"listInstancesJobID",params:null},
    {call:"listInstanceGroups",params:null},
#    {call:"enableUnattendedRebootAll",params:null},
#    {call:"getProxyConfig",params:null},
    {call:"updateAggregateData",params:null},
#    {call:"backupNetworkConfiguration",params:null},
    {call:"listUsersEx",params:null},
#    {call:"revertNetworkConfiguration",params:null},
    {call:"getHaConfig",params:null},
    {call:"getPowerStatusOverview",params:null},
    {call:"listApi",params:null},
    {call:"pvm_getAddress",params:null},
    {call:"getNTPInterval",params:null},
    {call:"disableSNMPTraps",params:null},
    {call:"runNetstat",params:null},
#    {call:"cancelNetworkChanges",params:null},
    {call:"getNTPServers",params:null},
    {call:"getPVMConfigNextStep",params:null},
    {call:"listNetworkRoutes",params:null},
    {call:"getHaStatus",params:null},
#    {call:"listClearLogJobs",params:null},
    {call:"meteringGetManagedClientInfo",params:null},
    {call:"getPVMConfigNextCli",params:null},
#    {call:"rebootSystem",params:null},
    {call:"pvm_getCACert",params:null},
    {call:"listRolesEx",params:null},
#    {call:"deleteSSLCertificate",params:null}
  ]