// Generated by CoffeeScript 1.6.2
(function() {
  var PVMSettings,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ko.components.register('settings', {
    viewModel: PVMSettings = (function() {
      function PVMSettings() {
        this.init = __bind(this.init, this);        this.init();
      }

      PVMSettings.prototype.init = function() {};

      return PVMSettings;

    })(),
    template: {
      require: "/static/requirejs/text.js!views?template=settings/settings"
    }
  });

}).call(this);

/*
//@ sourceMappingURL=pvmsettings.map
*/
